Algoritmo "area_do_retangulo"
// Professor   :Cintia Pinho
// Descrição   : este algoritmo calcula a area do retangulo
// Autor(a)    : Luiza Pereira Silva
// Data atual  : 12/03/2021
Var
// Seção de Declarações das variáveis 
base, altura, area:real


Inicio
//entrada
escreva("Digite a base do retangulo: ")
leia(base)
escreva("Digite a altura do retangulo: ")
leia(altura)

area <- area*altura

escreva("A area do retangulo e: ", area, "m2")



Fimalgoritmo