Algoritmo "area_do_quadrado"
// Professor   : Cintia Pinho
// Descrição   : Este algoritmo calcula a area do quadrado
// Autor(a)    : Luiza Pereira Silva
// Data atual  : 12/03/2021
Var
// Seção de Declarações das variáveis 
lado, area:real


Inicio
// entrada

escreva("Digite o lado do quadrado: ")
leia(lado)

//processamento
area <- lado*lado

//saida
escreva("A area do quadrado e: ", area, "m2")

Fimalgoritmo